update
inmanta/pytest-inmanta-lsm pull request #300
Opened 2023-03-29 08:31 UTC by FloLey

# Description

* Short description here *

closes *Add ticket reference here*

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors (check using make mypy or make mypy-diff)
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

2023-03-29 09:11 UTC, sanderr approved these changes

2023-03-29 12:28 UTC, sanderr requested changes

2023-03-29 12:49 UTC, FloLey commented on tests/utils.py
> +    if constraints and os.path.exists(project_dir / "module.yml"):
I think it is done now but not sure how to test it works :p

2023-04-04 07:33 UTC, sanderr commented on tests/utils.py
> +    if constraints and os.path.exists(project_dir / "module.yml"):
I would just try it manually: add a breakpoint in a test case that installs a v2 module, set the env var with a constraint, run the test and check the installed version.

2023-04-04 07:36 UTC, sanderr requested changes

2023-04-04 07:36 UTC, sanderr commented on tests/utils.py
> +            with open(project_dir / "requirements.txt", "a") as fh:
Oh, this won't work, my bad. V2 modules ignore `requirements.txt`, we need to add it to `setup.cfg`.

2023-04-04 12:15 UTC, sanderr approved these changes

2023-04-04 12:15 UTC, sanderr commented on tests/utils.py
> +                existing_requires = existing_requires + "\n"
It's a string, not a list?

2023-04-04 12:17 UTC, FloLey commented on tests/utils.py
> +                parser.write(fh)
oups, don't know how this happened.

2023-04-04 12:18 UTC, FloLey commented on tests/utils.py
> +                existing_requires = existing_requires + "\n"
yes it's a string; i'll add the typing

2023-04-04 12:29 UTC, merged